name: Release Automation

on:
  push:
    tags:
      - "final-project-v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip project files
        run: |
          mkdir -p upload/finalproject/code
          mkdir -p upload/finalproject/data
          mkdir -p upload/finalproject/docs

          cp finalproject/code/finalproject.qmd upload/finalproject/code/finalproject.qmd
          cp finalproject/code/finalproject.ipynb upload/finalproject/code/finalproject.ipynb
          cp finalproject/code/finalproject-rcode-output.pdf upload/finalproject/code/finalproject-rcode-output.pdf
          cp finalproject/data/finalproject.csv upload/finalproject/data/finalproject.csv

          cd upload
          zip -r finalproject.zip finalproject
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./upload/finalproject.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
