name: Release Automation

on:
  push:
    tags:
      - "final-project-v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip project files
        run: |
          mkdir upload
          cp -r finalproject upload/
          cd upload
          rm -f ./docs/finalproject-report.tex
          rm -f ./docs/finalproject-report.bib
          rm -rf ./docs/images
          zip -r finalproject.zip finalproject
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./upload/finalproject.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
